debugging to confirm files before deployment

diff --git a/.github/workflows/MainWorkflow.yml b/.github/workflows/MainWorkflow.yml
--- a/.github/workflows/MainWorkflow.yml
+++ b/.github/workflows/MainWorkflow.yml
@@ -76,14 +76,13 @@ jobs:
           mkdir -p cleanair_deploy/sql
           cp -r ./server/Infrastructure.Postgres/Migrations/* cleanair_deploy/sql/
 
-      - name: Verify staged SQL files
+      - name: Confirm files before deployment
         run: |
-          echo "Contents of cleanair_deploy/sql:"
-          if [ -d cleanair_deploy/sql ]; then
-            ls -al cleanair_deploy/sql
-          else
-            echo "Directory cleanair_deploy/sql does not exist!"
-          fi
+          echo "Files to be deployed:"
+          ls -al ./docker-compose.yml || echo "Missing docker-compose.yml"
+          ls -al .env || echo "Missing .env"
+          ls -al ./cleanair_deploy/sql || echo "Missing sql folder"
+          ls -al ./client/default.conf || echo "Missing default.conf"
     
     
       - name: Deploy to staging server
