Changed workflow, added debugging for migration files

diff --git a/.github/workflows/MainWorkflow.yml b/.github/workflows/MainWorkflow.yml
--- a/.github/workflows/MainWorkflow.yml
+++ b/.github/workflows/MainWorkflow.yml
@@ -11,20 +11,13 @@ permissions:
 
 jobs:
   delivery:
-    # needs: [integration]
     runs-on: ubuntu-latest
-    
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          
-      #- name: Semantic Application Version
-      #  id: semver-app
-      #  uses: paulhatch/semantic-version@v5.4.0
-      #  with:
-      #    bump_each_commit: true    
 
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v2
@@ -58,16 +51,24 @@ jobs:
           JWT_SECRET=${{ secrets.JWT_SECRET }}
           EOL
 
+      - run: |
+          echo "Checking contents of Migrations directory:"
+          ls -al ./server/Infrastructure.Postgres/Migrations || echo "Directory not found"
+          echo "Searching for .sql files recursively:"
+          find ./server -name "*.sql" || echo "No .sql files found"
+
       - name: Deploy to staging server
         uses: appleboy/scp-action@v0.1.7
         with:
           host: ${{ vars.STAGING_SERVER_IP }}
           username: ${{ vars.STAGING_SERVER_USERNAME }}
           key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
-          source: "./docker-compose.yml,.env,./server/infrastructure.Postgres/Migrations/**.sql,./client/default.conf"
+          source: |
+            ./docker-compose.yml
+            .env
+            ./server/Infrastructure.Postgres/Migrations/**
+            ./client/default.conf
           target: cleanair/
-          
-          
 
       - name: Start containers on staging server
         uses: appleboy/ssh-action@v1.2.1
